/**
 * Mellov API
 * Mellov API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NoteItem model module.
 * @module model/NoteItem
 * @version 1.1.0
 */
class NoteItem {
    /**
     * Constructs a new <code>NoteItem</code>.
     * @alias module:model/NoteItem
     * @param creationDate {String} 
     * @param text {String} 
     */
    constructor(creationDate, text) { 
        
        NoteItem.initialize(this, creationDate, text);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, creationDate, text) { 
        obj['creationDate'] = creationDate;
        obj['text'] = text;
    }

    /**
     * Constructs a <code>NoteItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NoteItem} obj Optional instance to populate.
     * @return {module:model/NoteItem} The populated <code>NoteItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NoteItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NoteItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NoteItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NoteItem.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['creationDate'] && !(typeof data['creationDate'] === 'string' || data['creationDate'] instanceof String)) {
            throw new Error("Expected the field `creationDate` to be a primitive type in the JSON string but got " + data['creationDate']);
        }
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}

NoteItem.RequiredProperties = ["creationDate", "text"];

/**
 * @member {String} id
 */
NoteItem.prototype['id'] = undefined;

/**
 * @member {String} creationDate
 */
NoteItem.prototype['creationDate'] = undefined;

/**
 * @member {String} text
 */
NoteItem.prototype['text'] = undefined;






export default NoteItem;

