/**
 * Mellov API
 * Mellov API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SongItem from '../model/SongItem';
import TagItem from '../model/TagItem';
import YtVideoItem from '../model/YtVideoItem';

/**
* Users service.
* @module api/UsersApi
* @version 1.0.0
*/
export default class UsersApi {

    /**
    * Constructs a new UsersApi. 
    * @alias module:api/UsersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Search songs
     * Find songs
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip number of records to skip for pagination
     * @param {Number} opts.limit maximum number of records to return
     * @param {String} opts.title a phrase song's title must contain
     * @param {Array.<String>} opts.tags tags which song must contain
     * @param {String} opts.sort type of sort to use
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/SongItem>} and HTTP response
     */
    searchSongsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit'],
        'title': opts['title'],
        'tags': this.apiClient.buildCollectionParam(opts['tags'], 'multi'),
        'sort': opts['sort']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['MellovAuthorizer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SongItem];
      return this.apiClient.callApi(
        '/songs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search songs
     * Find songs
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip number of records to skip for pagination
     * @param {Number} opts.limit maximum number of records to return
     * @param {String} opts.title a phrase song's title must contain
     * @param {Array.<String>} opts.tags tags which song must contain
     * @param {String} opts.sort type of sort to use
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/SongItem>}
     */
    searchSongs(opts) {
      return this.searchSongsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search tags
     * Find tags
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip number of records to skip for pagination
     * @param {Number} opts.limit maximum number of records to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TagItem>} and HTTP response
     */
    searchTagsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'skip': opts['skip'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['MellovAuthorizer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TagItem];
      return this.apiClient.callApi(
        '/tags', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search tags
     * Find tags
     * @param {Object} opts Optional parameters
     * @param {Number} opts.skip number of records to skip for pagination
     * @param {Number} opts.limit maximum number of records to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TagItem>}
     */
    searchTags(opts) {
      return this.searchTagsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Search yt items
     * Find yt items
     * @param {String} title title to search
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit maximum number of records to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/YtVideoItem>} and HTTP response
     */
    searchYtItemsWithHttpInfo(title, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'title' is set
      if (title === undefined || title === null) {
        throw new Error("Missing the required parameter 'title' when calling searchYtItems");
      }

      let pathParams = {
      };
      let queryParams = {
        'title': title,
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['MellovAuthorizer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [YtVideoItem];
      return this.apiClient.callApi(
        '/yt-items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Search yt items
     * Find yt items
     * @param {String} title title to search
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit maximum number of records to return
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/YtVideoItem>}
     */
    searchYtItems(title, opts) {
      return this.searchYtItemsWithHttpInfo(title, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
