/**
 * Mellov API
 * Mellov API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ItemCreated from './model/ItemCreated';
import NoteItem from './model/NoteItem';
import SongItem from './model/SongItem';
import TagItem from './model/TagItem';
import YtVideoItem from './model/YtVideoItem';
import CORSApi from './api/CORSApi';
import UsersApi from './api/UsersApi';


/**
* Mellov API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MellovApi = require('index'); // See note below*.
* var xxxSvc = new MellovApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MellovApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MellovApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MellovApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ItemCreated model constructor.
     * @property {module:model/ItemCreated}
     */
    ItemCreated,

    /**
     * The NoteItem model constructor.
     * @property {module:model/NoteItem}
     */
    NoteItem,

    /**
     * The SongItem model constructor.
     * @property {module:model/SongItem}
     */
    SongItem,

    /**
     * The TagItem model constructor.
     * @property {module:model/TagItem}
     */
    TagItem,

    /**
     * The YtVideoItem model constructor.
     * @property {module:model/YtVideoItem}
     */
    YtVideoItem,

    /**
    * The CORSApi service constructor.
    * @property {module:api/CORSApi}
    */
    CORSApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
