/**
 * Mellov API
 * Mellov API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class YtVideoItem {
    'title'?: string;
    'videoId'?: string;
    'thumbnailUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "videoId",
            "baseName": "videoId",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnailUrl",
            "baseName": "thumbnailUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return YtVideoItem.attributeTypeMap;
    }

    public constructor() {
    }
}

